#!/usr/bin/env bash
set -euo pipefail

commit_msg_file="${1:-}"

if [ -z "$commit_msg_file" ] || [ ! -f "$commit_msg_file" ]; then
  echo "  [commit-msg] ERROR: No commit message file provided."
  exit 1
fi

# Strip comment lines (lines starting with #).
# Also strip "Made-with:" trailers which some tooling may inject automatically.
full_msg=$(
  grep -v '^#' "$commit_msg_file" \
    | grep -viE '^[[:space:]]*made-with:' \
    || true
)
# First non-blank line for conventional commit format check
commit_msg=$(echo "$full_msg" | sed '/^[[:space:]]*$/d' | head -1)

if [ -z "$commit_msg" ]; then
  echo "  [commit-msg] ERROR: Empty commit message."
  exit 1
fi

# --- Conventional commits format check ---
# Format: type(scope): description  OR  type: description
# Type must be one of the allowed set. Description 1-100 chars.
conventional_pattern="^(feat|fix|chore|docs|style|refactor|test|perf|ci|build|revert)(\([^)]+\))?: .{1,100}$"

if ! echo "$commit_msg" | grep -qE "$conventional_pattern"; then
  echo ""
  echo "  [commit-msg] BLOCKED: Commit message does not follow conventional commits format."
  echo ""
  echo "  Format  : type(scope): description"
  echo "  Types   : feat | fix | chore | docs | style | refactor | test | perf | ci | build | revert"
  echo "  Example : feat(auth): add JWT refresh endpoint"
  echo "  Example : fix: handle null user in session"
  echo ""
  echo "  Your message: \"$commit_msg\""
  exit 1
fi

# --- AI agent reference check ---
# Case-insensitive. Blocks common AI tool/agent signatures.
ai_patterns="claude|cursor|copilot|co-author|co_author|coauthor|made with|generated by|ai agent|chatgpt|gemini|windsurf|codeium|tabnine|github copilot"

if echo "$full_msg" | grep -qiE "$ai_patterns"; then
  matched=$(echo "$full_msg" | grep -oiE "$ai_patterns" | head -1)
  echo ""
  echo "  [commit-msg] BLOCKED: Commit message contains an AI agent reference: \"$matched\""
  echo ""
  echo "  Your message: \"$commit_msg\""
  exit 1
fi

exit 0
